# Generated by Django 6.1 on 2026-08-29 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief description of the task', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed notes, links, sub-tasks')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], db_index=True, default='pending', help_text='Current state of the task', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', help_text='Urgently level', max_length=20)),
                ('category', models.CharField(blank=True, db_index=True, default='', help_text='Context label (e.g., work, personal)', max_length=50)),
                ('due_date', models.DateField(blank=True, db_index=True, help_text='Deadline (optional)', null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='The owner of this task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='tasks_user_id_a53e17_idx'), models.Index(fields=['user', 'priority'], name='tasks_user_id_e06a45_idx'), models.Index(fields=['user', 'category'], name='tasks_user_id_b12e38_idx'), models.Index(fields=['user', 'due_date'], name='tasks_user_id_20dbf7_idx')],
            },
        ),
    ]
